apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "missing-container-metrics.fullname" . }}
  labels:
    {{- include "missing-container-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "missing-container-metrics.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "missing-container-metrics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
      {{- if .Values.useDocker}}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      {{- end }}
      {{- if .Values.useContainerd}}
      - name: containerdsock
        hostPath:
          path: {{ .Values.containerdSocketPath }}
      {{- end }}
      {{- if .Values.tolerations  }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DOCKER
          {{- if .Values.useDocker}}
              value: "true"
          {{- else }}
              value: "false"
          {{- end }}
            - name: CONTAINERD
          {{- if .Values.useContainerd}}
              value: "true"
          {{- else }}
              value: "false"
          {{- end }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.useDocker}}
          - name: dockersock
            mountPath: /var/run/docker.sock
          {{- end }}
          {{- if .Values.useContainerd}}
          - name: containerdsock
            mountPath: /run/containerd/containerd.sock
          {{- end}}
