name: Package and publish helm chart to Github Pages
on:
  push:
    tags:
      - 'v*'

jobs:
  helm_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        run: |
          echo "::set-output name=CHART_VERSION::${GITHUB_REF_NAME:1}"
        id: version
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_version: ${{ steps.version.outputs.CHART_VERSION }}
          app_version: ${{ steps.version.outputs.CHART_VERSION }}

